export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOAD_USER = "LOAD_USER";

export const FORM_DATA = "FORM_DATA";
export const FORM_DELETE = "FORM_DELETE";
export const FORM_APPROVE = "FORM_APPROVE";
export const FORM_REJECT = "FORM_REJECT";

export const ADD_DATA_LOADING = "ADD_DATA_LOADING";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_ERROR = "ADD_DATA_ERROR";
export const CLEAR_ADD_DATA_ERROR = "CLEAR_ADD_DATA_ERROR";

export const FETCH_DATA_LOADING = "FETCH_DATA_LOADING";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";

export const FETCH_DATA_SUCCESS_NEWS = "FETCH_DATA_SUCCESS_NEWS";
export const FETCH_DATA_NEWS_DETAIL = "FETCH_DATA_NEWS_DETAIL";

export const FETCH_DATA_SUCCESS_MEMBERS = "FETCH_DATA_SUCCESS_MEMBERS";
//export const FETCH_DATA_SUCCESS_SATGAS = "FETCH_DATA_SUCCESS_SATGAS";

export const CHG_PROPS = "CHG_PROPS";

export const FETCH_DATA_PENGADUAN = "FETCH_DATA_PENGADUAN";
export const SHOW_CONFIRM_ONPROGRESS = "SHOW_CONFIRM_ONPROGRESS";
export const CONFIRM_ONPROGRESS_SUCCESS = "CONFIRM_ONPROGRESS_SUCCESS";
export const CONFIRM_LOADING = "CONFIRM_LOADING";
export const SHOW_CONFIRM_COMPLETE = "SHOW_CONFIRM_COMPLETE";

export const FETCH_DATA_MKASUS = "FETCH_DATA_MKASUS";
export const FETCH_DATA_ADMIN = "FETCH_DATA_ADMIN";

export const FETCH_DATA_USER = "FETCH_DATA_USER";
export const FETCH_DATA_ROLE = "FETCH_DATA_ROLE";
export const FETCH_DATA_BANK = "FETCH_DATA_BANK";
export const FETCH_DATA_NEGARA = "FETCH_DATA_NEGARA";
export const FETCH_DATA_PROVINSI = "FETCH_DATA_PROVINSI";
export const FETCH_DATA_KOTA = "FETCH_DATA_KOTA";
export const FETCH_DATA_CABANG = "FETCH_DATA_CABANG";
export const FETCH_DATA_RATE = "FETCH_DATA_RATE";
export const FETCH_DATA_TIPE_AKUN = "FETCH_DATA_TIPE_AKUN";
export const FETCH_DATA_LIST_GROUP = "FETCH_DATA_LIST_GROUP";
export const FETCH_DATA_SETTING = "FETCH_DATA_SETTING";
export const FETCH_DATA_REF_CODE = "FETCH_DATA_REF_CODE";
export const FETCH_DATA_AKUN_TERPISAH = "FETCH_DATA_AKUN_TERPISAH";
export const FETCH_SUSUNAN_PENGURUS = "FETCH_SUSUNAN_PENGURUS";
export const FETCH_SUSUNAN_SAHAM = "FETCH_SUSUNAN_SAHAM";
export const FETCH_PROFILE_PERUSAHAAN = "FETCH_PROFILE_PERUSAHAAN";
export const FETCH_LEGALITAS_PERUSAHAAN = "FETCH_LEGALITAS_PERUSAHAAN";
export const FETCH_DATA_BANNER = "FETCH_DATA_BANNER";
export const FETCH_DATA_SETORAN = "FETCH_DATA_SETORAN";
export const FETCH_DATA_SUCCESS_EXPORT_SETORAN = "FETCH_DATA_SUCCESS_EXPORT_SETORAN";
export const FETCH_DATA_PENARIKAN = "FETCH_DATA_PENARIKAN";
export const FETCH_DATA_SUCCESS_EXPORT_PENARIKAN = "FETCH_DATA_SUCCESS_EXPORT_PENARIKAN";

export const FETCH_DATA_BANK_PERUSAHAAN = "FETCH_DATA_BANK_PERUSAHAAN";
export const FETCH_DATA_CONTACTUS = "FETCH_DATA_CONTACTUS";
export const FETCH_DATA_AKUN_DEMO = "FETCH_DATA_AKUN_DEMO";
export const FETCH_DATA_TEMPLATE_EMAIL = "FETCH_DATA_TEMPLATE_EMAIL";

export const FETCH_DATA_ARTIKEL = "FETCH_DATA_ARTIKEL";
export const FETCH_DATA_LISTAPPROVE = "FETCH_DATA_LISTAPPROVE";

export const FETCH_DATA_TRANSFER = "FETCH_DATA_TRANSFER";

export const FETCH_DATA_DEL_BANK = "FETCH_DATA_DEL_BANK";
export const FETCH_DATA_NEW_BANK = "FETCH_DATA_NEW_BANK";
export const FETCH_DATA_EDIT_EMAIL = "FETCH_DATA_EDIT_EMAIL";
// export const FORM_APPROVE = "FORM_APPROVE";
